name: Build MagicQuests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download project
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build MagicQuests
        run: mvn --batch-mode clean package

      - name: Upload MagicQuests JAR
        uses: actions/upload-artifact@v4
        with:
          name: MagicQuests
          path: target/MagicQuests.jar
          if-no-files-found: error
